apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multiarch-manager-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multiarch-manager-operator
    app.kubernetes.io/part-of: multiarch-manager-operator
  name: multiarch-manager-operator
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: multiarch-manager-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: multiarch-manager-operator
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/psundara-tenant/multiarch-manager-operator/multiarch-manager-operator@sha256:272d6d3dc102449a124b4d06bfb25a01a451bb4df684140901c7d6cfb5f914a0
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 5001
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
